#!/bin/bash
set -ex

apt-get update -qq

echo ""
echo "--------------------------------------------------------------------------------"
echo "Install packages:"

# Force stop to prevent conflict with existing PostgreSQL
# /etc/init.d/postgresql stop

# Install needed packages including PostgreSQL
# echo "Removing old Postgres versions."
# apt-get remove postgresql-client-9.1 postgresql-client-9.2 postgresql-client-9.3 postgresql-client-9.4 postgresql-client-9.5
echo""
echo "Dependencies install..."
echo""
apt-get install -f -q qt5-qmake graphicsmagick tesseract-ocr tesseract-ocr-fra tesseract-ocr-eng tesseract-ocr-spa pdftk libreoffice poppler-utils poppler-data qt5-default libqt5webkit5-dev gstreamer1.0-x gstreamer1.0-tools gstreamer1.0-plugins-base libgeos-dev libproj-dev || true
gem uninstall bundler -a -x && gem install bundler -v 1.14.6
echo ""
echo "Dependencies installed!"
echo ""

gem install capybara-webkit -v '1.15.0'

# # Configure PostgreSQL port to 5432
# sed -i -r 's/port\s*=\s*[0-9]+/port = 5432/g' /etc/postgresql/9.6/main/postgresql.conf

# # Grant access to all
# sed -i '1i local all all trust' /etc/postgresql/9.6/main/pg_hba.conf

# # Force PostgreSQL restart
# /etc/init.d/postgresql stop
# /etc/init.d/postgresql start 9.6
