dependencies:
  build:
    - ruby:2.6.0
    - java:8.202.08

build_targets:
  - name: default
    container: 
      image: yourbase/yb_ubuntu:16.04
    commands:
        - chmod +x yourbased.sh
        - ./yourbased.sh
    environment:
      - PGUSER=ci
      - PGPASSWORD=ci
      - PGHOST={{ .Containers.IP "postgres" }}
      - DATABASE_URL=postgres://ci:ci@{{ .Containers.IP "postgres" }}:5432/travis_ci_test
    dependencies:
      containers:
        redis:
          image: redis:latest
          port_check:
            port: 6379
            timeout: 20
        postgres:
          image: postgres:9.4
          environment:
            - POSTGRES_PASSWORD=root
            - POSTGRES_USER=root
            - POSTGRES_DB=travis_ci_test
          port_check:
            port: 5432
            timeout: 45
    
      
     
ci:
  builds:
    - name: default
      build_target: default
